### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by wuhu201314** [Well2333/nonebot-plugin-mongodb#2]
![image](https://github.com/Well2333/nonebot-plugin-mongodb/assets/130721000/720639cf-7a83-420c-9ccf-4c663527b2b3)

**Comment by Well2333** [comment]
你需要在 env 中填入 `mongo_uri` 来连接 mongodb 数据库

注意，这 **不是** 一个功能性插件，此插件 **没有** 任何面向用户的功能，如果你是普通用户请 **不要** 安装此插件
